### ISSUE TITLE
Request to update speaker registration link

### ISSUE THREAD

**Issue by mielamvn** [fossasia/2019.fossasia.org#4]
Please help to add the link for speaker registration.

The link is here: https://eventyay.com/e/3689bc98/cfs/

Thank you

**Comment by MadhavBahlMD** [comment]
Hey @mielamvn I can do it, I couldn't find a link for speaker registration at https://2019.fossasia.org/

Should I create a button/link and link it to https://eventyay.com/e/3689bc98/cfs/ ?

**Comment by mielamvn** [comment]
Hi Madhav, you can do something similar to this website: https://2017.fossasia.org/

Thanks

**Comment by MadhavBahlMD** [comment]
Hey @mielamvn, instead of speaker registration button, there's a get schedule button in 2019.fossasia.org
Should I replace it with speaker registration or add another button for speaker registration?

2017.fossasia.org -
![image](https://user-images.githubusercontent.com/26179770/44909102-a94ef580-ad3b-11e8-9240-4cb1c2f162d3.png)

2019.fossasia.org - 
![image](https://user-images.githubusercontent.com/26179770/44909115-b53ab780-ad3b-11e8-984e-83897f965aec.png)

**Comment by hpdang** [comment]
yes, please
